echo Changing dir to pa11y mock server...
cd test/mee.identity.pa11y/src/mocks

echo Installing client dependencies...
npm ci --prefer-offline --no-audit

echo Copy files...
COPY ./src .

echo Testing client Assets...
npm run start:server
